ildeposito_raw.settings:
  type: config_object
  label: 'Impostazioni Il Deposito Raw'
  mapping:
    cache_max_age:
      type: integer
      label: 'Durata massima della cache'
    raw_entities:
      type: sequence
      label: 'Entità con elaborazione raw'
      sequence:
        type: mapping
        mapping:
          entity_type:
            type: string
            label: 'Tipo di entità'
          bundles:
            type: sequence
            label: 'Bundle'
            sequence:
              type: string
          view_modes:
            type: sequence
            label: 'View modes'
            sequence:
              type: string